### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by leppert**
Fixes https://github.com/plumatic/plumbing/pull/96 along with a few other warnings.

### CODE REVIEW

**Comment by moea** [comment]
@leppert Thanks!

**Comment by leppert** [comment]
@moea 🎉 Any thoughts on pushing a new release to Clojars?

**Comment by moea** [comment]
@leppert 0.4.5-SNAPSHOT is up to date with [this branch](https://github.com/nervous-systems/hildebrand/compare/release/0.4.5) - there were some issues with the boolean? change (compiler issues due to clojure 1.8 & cljs 1.9.x, and an import issue) so I took a slightly different approach, and released a new eulalie version with more up-to-date dependencies.

**Comment by leppert** [comment]
@moea Ah! Sorry about that, and thank you.

**Pull request merged**
